# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test python package

on:
  pull_request:
    branches: [ "develop", "master"]
  push:
    branches: [ "develop", "master"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: |
            3.8
            3.9
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        pip install -U pip wheel
        pip install --install-option="--no-cython-compile" cython
        pip install -r dev-requirements.txt
        python setup.py develop
    - name: Test package
      run: |
        python -m pytest --showlocals --pyargs
        black --check inverse_covariance
        black --check examples
