# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python Package

on:
  push:
    branches: [ "master"]

permissions:
  contents: read

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [3.8, 3.9]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    # - uses: actions/checkout@v3
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.version }}
    # - name: Install dependencies
    #   run: |
    #     pip install -U pip wheel
    #     pip install --install-option="--no-cython-compile" cython
    #     pip install -r dev-requirements.txt
    #     python setup.py develop
    # - name: Test package
    #   run: |
    #     python -m pytest --showlocals --pyargs
    #     black --check inverse_covariance
    #     black --check examples
      - uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2010_x86_64
        name: Build
        with:
          python-versions: 'cp39-cp39'
          build-requirements: 'cython numpy scipy'
          pip-wheel-args: '-w ./dist'
    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
